openapi: "3.0.0"
info:
  title: Airella API
  version: 1.0.0
paths:
  /auth/login:
    post:
      operationId: login
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: |-
            User logged in succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: object
                    properties:
                      token:
                        type: string
                      expirationDate:
                        type: string
                  refreshToken:
                    type: string
                  stationRegistrationToken:
                    type: string
        '403':
          description: |-
            Bad credentials
  /auth/refresh-token:
    post:
      operationId: refresh-token
      summary: Refresh user access token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: |-
            User logged in succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expirationDate:
                    type: string
        '403':
          description: |-
            Bad refresh token
  /auth/register-user:
    post:
      operationId: register-user
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: |-
            User created
        '400':
          description: |-
            This username is already taken
        '403':
          description: |-
            Bad refresh token
  /auth/register-station:
    post:
      operationId: register-station
      summary: Register new station
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                stationRegistrationToken:
                  type: string
      responses:
        '200':
          description: |-
            New station registered successfully. Returns refreshToken of newly registered station.
          content:
            application/json:
              schema:
                type: object
                properties:
                  refreshToken:
                    type: string
                    description: "Token of newly registered station"
        '400':
          description: |-
            Bad stationRegistrationToken
        '403':
          description: |-
            Bad refresh token