--liquibase formatted sql

--changeset jakubdybczak:1596572061426-1
CREATE TABLE address (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city VARCHAR(255), country VARCHAR(255), number VARCHAR(255), street VARCHAR(255), CONSTRAINT "addressPK" PRIMARY KEY (id));

--changeset jakubdybczak:1596572061426-2
CREATE TABLE client (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, refresh_token VARCHAR(255), CONSTRAINT "clientPK" PRIMARY KEY (id));

--changeset jakubdybczak:1596572061426-3
CREATE TABLE client_role (id BIGINT NOT NULL, roles VARCHAR(255));

--changeset jakubdybczak:1596572061426-4
CREATE TABLE measurement (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP WITHOUT TIME ZONE, value FLOAT8 NOT NULL, sensor_db_id BIGINT, CONSTRAINT "measurementPK" PRIMARY KEY (id));

--changeset jakubdybczak:1596572061426-5
CREATE TABLE sensor (db_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id VARCHAR(255), type VARCHAR(255), latest_measurement_id BIGINT, station_db_id BIGINT, CONSTRAINT "sensorPK" PRIMARY KEY (db_id));

--changeset jakubdybczak:1596572061426-6
CREATE TABLE station (db_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id VARCHAR(255), latitude FLOAT8 NOT NULL, longitude FLOAT8 NOT NULL, name VARCHAR(255), station_visibility VARCHAR(255), address_id BIGINT, owner_id BIGINT, station_client_id BIGINT, CONSTRAINT "stationPK" PRIMARY KEY (db_id));

--changeset jakubdybczak:1596572061426-7
CREATE TABLE station_client (id BIGINT NOT NULL, CONSTRAINT "station_clientPK" PRIMARY KEY (id));

--changeset jakubdybczak:1596572061426-8
CREATE TABLE statistic (db_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id VARCHAR(255), statistic_privacy_mode VARCHAR(255), statistic_type VARCHAR(255), station_db_id BIGINT, CONSTRAINT "statisticPK" PRIMARY KEY (db_id));

--changeset jakubdybczak:1596572061426-9
CREATE TABLE statistic_value (db_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP WITHOUT TIME ZONE, statistic_db_id BIGINT, CONSTRAINT "statistic_valuePK" PRIMARY KEY (db_id));

--changeset jakubdybczak:1596572061426-10
CREATE TABLE statistic_value_double (value FLOAT8 NOT NULL, db_id BIGINT NOT NULL, CONSTRAINT "statistic_value_doublePK" PRIMARY KEY (db_id));

--changeset jakubdybczak:1596572061426-11
CREATE TABLE statistic_value_string (string VARCHAR(255), db_id BIGINT NOT NULL, CONSTRAINT "statistic_value_stringPK" PRIMARY KEY (db_id));

--changeset jakubdybczak:1596572061426-12
CREATE TABLE user_client (email VARCHAR(255), password_hash VARCHAR(255), station_registration_token VARCHAR(255), id BIGINT NOT NULL, CONSTRAINT "user_clientPK" PRIMARY KEY (id));

--changeset jakubdybczak:1596572061426-13
CREATE TABLE user_client_stub (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, activate_string VARCHAR(255), email VARCHAR(255), password_hash VARCHAR(255), CONSTRAINT "user_client_stubPK" PRIMARY KEY (id));

--changeset jakubdybczak:1596572061426-14
ALTER TABLE client ADD CONSTRAINT UC_CLIENTREFRESH_TOKEN_COL UNIQUE (refresh_token);

--changeset jakubdybczak:1596572061426-15
ALTER TABLE station ADD CONSTRAINT UC_STATIONID_COL UNIQUE (id);

--changeset jakubdybczak:1596572061426-16
ALTER TABLE user_client ADD CONSTRAINT UC_USER_CLIENTEMAIL_COL UNIQUE (email);

--changeset jakubdybczak:1596572061426-17
ALTER TABLE user_client_stub ADD CONSTRAINT UC_USER_CLIENT_STUBEMAIL_COL UNIQUE (email);

--changeset jakubdybczak:1596572061426-18
ALTER TABLE statistic ADD CONSTRAINT "UK84hkw6bkpo2lbbekbq0wy1k3a" UNIQUE (station_db_id, id);

--changeset jakubdybczak:1596572061426-19
ALTER TABLE sensor ADD CONSTRAINT "UKe1xtqt35tarjrusx7y1rtx3vs" UNIQUE (station_db_id, id);

--changeset jakubdybczak:1596572061426-20
CREATE INDEX INDX_0 ON measurement(timestamp);

--changeset jakubdybczak:1596572061426-21
ALTER TABLE statistic ADD CONSTRAINT "FK20np2syxcj308c7xcygxo717w" FOREIGN KEY (station_db_id) REFERENCES station (db_id);

--changeset jakubdybczak:1596572061426-22
ALTER TABLE station ADD CONSTRAINT "FK4qcdqbyfa4u1tpxhhskj6cvek" FOREIGN KEY (station_client_id) REFERENCES station_client (id);

--changeset jakubdybczak:1596572061426-23
ALTER TABLE station ADD CONSTRAINT "FK52qw87l9ttkr3nf32phsvqe6f" FOREIGN KEY (address_id) REFERENCES address (id);

--changeset jakubdybczak:1596572061426-24
ALTER TABLE sensor ADD CONSTRAINT "FK88wiltqsbte20tvhvd60siapm" FOREIGN KEY (latest_measurement_id) REFERENCES measurement (id);

--changeset jakubdybczak:1596572061426-25
ALTER TABLE statistic_value ADD CONSTRAINT "FKa3gf9a84cbhck12sops84lw8p" FOREIGN KEY (statistic_db_id) REFERENCES statistic (db_id);

--changeset jakubdybczak:1596572061426-26
ALTER TABLE measurement ADD CONSTRAINT "FKa5ehlq2tq9buy8sjxtuk7el85" FOREIGN KEY (sensor_db_id) REFERENCES sensor (db_id);

--changeset jakubdybczak:1596572061426-27
ALTER TABLE sensor ADD CONSTRAINT "FKbdp56mm8l0qu4ujmubmroqvbh" FOREIGN KEY (station_db_id) REFERENCES station (db_id);

--changeset jakubdybczak:1596572061426-28
ALTER TABLE station_client ADD CONSTRAINT "FKbkmmakw2c5qmjuh3qh22lrjsy" FOREIGN KEY (id) REFERENCES client (id);

--changeset jakubdybczak:1596572061426-29
ALTER TABLE station ADD CONSTRAINT "FKck6b3rbj8cq68osm122c726ns" FOREIGN KEY (owner_id) REFERENCES user_client (id);

--changeset jakubdybczak:1596572061426-30
ALTER TABLE statistic_value_double ADD CONSTRAINT "FKeuejsfdt5xml3amwfdy4eptfd" FOREIGN KEY (db_id) REFERENCES statistic_value (db_id);

--changeset jakubdybczak:1596572061426-31
ALTER TABLE user_client ADD CONSTRAINT "FKgdrjsb0tj0tk2yb6iibukfh4e" FOREIGN KEY (id) REFERENCES client (id);

--changeset jakubdybczak:1596572061426-32
ALTER TABLE client_role ADD CONSTRAINT "FKlc5c40lwdi77xfj5jlrwpt4uc" FOREIGN KEY (id) REFERENCES client (id);

--changeset jakubdybczak:1596572061426-33
ALTER TABLE statistic_value_string ADD CONSTRAINT "FKr3s34xtbay7fcq89xbim08syv" FOREIGN KEY (db_id) REFERENCES statistic_value (db_id);

